### ISSUE TITLE
prevent game play after wrong answer

### ISSUE THREAD

**Issue by itaditya** [itaditya/got-death-quiz#2]
Currently the user can continue playing the game even after selecting wrong answer by pressing the other button. We need to prevent that. One way to do it is, after game over, hide the question and options, instead show game over text and ask user to reload page to play again.

**Issue will only be assigned to people I'm mentoring under Road to Hacktober programme. Other people please find other repos of mine to contribute for Hacktoberfest.**

**Comment by Srihari44** [comment]
I'll try this one.

**Comment by Srihari44** [comment]
#2 done with my PR #9!

**Comment by itaditya** [comment]
@Srihari44 left some comments.

**Comment by Srihari44** [comment]
Fixed as per your review #14
