### ISSUE TITLE
Add a link of contributors in the footer.

### ISSUE THREAD

**Issue by itaditya** [itaditya/got-death-quiz#4]
Add a section in the Readme listing all the contributors in this project. Then put that link in the footer of the game saying 'Made by awesome people'. And people is an anchor tag which goes to that link

**Issue will only be assigned to people I'm mentoring under Road to Hacktober programme. Other people please find other repos of mine to contribute for Hacktoberfest.**

**Comment by khusharth** [comment]
In the contributors section do you just want names of people who have contributed? And by *that link* do you mean the link to README.md file?

**Comment by itaditya** [comment]
In the footer there would be just this line.
```
Made by these awesome people.
```

And the `awesome people` would be a hyperlink which will open the Readme's Contributor section in a new tab.

**Comment by khusharth** [comment]
Ok i will try this.

**Comment by khusharth** [comment]
Should i leave the line *Made for Hacktoberfest by these awesome people* in the left corner or should i center it ?
![footer](https://user-images.githubusercontent.com/46857858/66651412-8ede8f80-ec50-11e9-93c2-5374234273aa.png)

**Comment by itaditya** [comment]
center it and use bold white text for link

**Comment by itaditya** [comment]
Use this link for Contributors https://github.com/itaditya/got-death-quiz#contributors
