### ISSUE TITLE
Add a button to replay the game without refreshing page.

### ISSUE THREAD

**Issue by itaditya** [itaditya/got-death-quiz#5]
We need to add a button for restarting game so user doesn't have to reload the entire page.

**Comment by martin-gnodtke** [comment]
Hi, I would like to work on that!

**Comment by ashimasingla20** [comment]
Is this done ? 
Can i work on this ?

**Comment by martin-gnodtke** [comment]
@ashimasingla20 Hey, I am sorry as I wrote in my PR my internet provider was down for 4 days. I committed my changes few minutes ago. 
I hope i didn't steal you some time working on this. Sorry for this inconvenience.

**Comment by itaditya** [comment]
Congrats @Squizzi3, you surpassed my expectations with your awesome work! Keep it up.
