### ISSUE TITLE
Store the highest streak in localStorage and show it on the right side

### ISSUE THREAD

**Issue by itaditya** [itaditya/got-death-quiz#6]
We can tell the user what the last highest streak was and so they have an incentive to play the game.

**Comment by hirohaji** [comment]
I can make this. See if it's like you want.

**Comment by newvertex** [comment]
@itaditya Hi, I've sent a PR (https://github.com/itaditya/got-death-quiz/pull/27) for this issue, I've added store high score to localStorage and show the last high score in the right section, feel free to comment or ask anything. ;-)
