### ISSUE TITLE
Add Light of The Seven song clip in the background

### ISSUE THREAD

**Issue by itaditya** [itaditya/got-death-quiz#7]
Add background music to further enhance the game intensity. Steps to do this task-

* Find the song file online and compress it and trim it so it is around 800KB. We don't need the whole song just the main part of it which we can then play in a loop.
* Use the `audio` tag of HTML5 for the audio with `volume` set to low and `loop` attribute must be present.
* Avoid the autoplay attribute since browsers now avoid playing audio before user-interaction. What you have to do is add an event listener for click on the page. Once they click anywhere on the page then play the audio.

**Comment by martin-gnodtke** [comment]
I would like to work on that :smiley:

**Comment by itaditya** [comment]
great, go ahead!

**Comment by itaditya** [comment]
merged by @Squizzi3
