### ISSUE TITLE
Add fade-in animation for the question text.

### ISSUE THREAD

**Issue by itaditya** [itaditya/got-death-quiz#8]
Using keyframes and opacity we can make a fade-in effect so when the question changes, the transition happens smoothly.

Note- Do not use 3rd party library like animate.css for this.

**Issue will only be assigned to people I'm mentoring under Road to Hacktober programme. Other people please find other repos of mine to contribute for Hacktoberfest.**

**Comment by ashimasingla20** [comment]
Can i please work on this issue ?

**Comment by itaditya** [comment]
Sure, go ahead!

**Comment by shivanshBTW** [comment]
I would love to work on this if this is still open

**Comment by shivanshBTW** [comment]
added in #25

**Comment by itaditya** [comment]
Great job @ashimasingla20
